baseURL = 'https://Oracledelphio.github.io/'
languageCode = 'en-us'
title = 'Welcome to My Page'
theme ='PaperMod'

[[menu.main]]
name = "Home"
identifier = "home"
url = "/"
weight = 20

[[menu.main]]
name = "Tags"
identifier = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
name = "Archives"
identifier = "archives"
url = "/archives/"
weight = 20

[[menu.main]]
name = "Twitter"
url = "https://twitter.com/elonmusk?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"

[[menu.main]]
name = "Youtube"
url = "https://youtu.be/dQw4w9WgXcQ?si=fYof2CJmJ_f5lzTD"


